### ISSUE TITLE
This project (might) violate GitHub Terms of Service.

### ISSUE THREAD

**Issue by ritabratamaiti** [gitx-io/ActionServerless#2]
See this: [https://docs.github.com/en/github/site-policy/github-additional-product-terms#5-actions-and-packages](https://docs.github.com/en/github/site-policy/github-additional-product-terms#5-actions-and-packages)

Relevant info from the page: 

> Actions and any elements of the Actions service may not be used in violation of the Agreement, the GitHub Acceptable Use Polices, or the GitHub Actions service limitations set forth in the Actions documentation. Additionally, Actions should not be used for:
> - cryptomining;
> - using our servers to disrupt, or to gain or to attempt to gain unauthorized access to, any service, device, data, account, or network (other than those authorized by the GitHub Bug Bounty program);
> - the provision of a stand-alone or integrated application or service offering Actions or any elements of Actions for commercial purposes;
> - any activity that places a burden on our servers, where that burden is disproportionate to the benefits provided to users (for example, don't use Actions as a content delivery network or as part of a serverless application, but a low benefit Action could be ok if it’s also low burden); or
> - any other activity unrelated to the production, testing, deployment, or publication of the software project associated with the repository where GitHub Actions are used.

**Comment by domano** [comment]
> * [...] or as part of a serverless application, [...]

It is specifically mentioned and is a violation as all the other serverless GH Actions repos that were killed

**Comment by gingerhot** [comment]
@ritabratamaiti @domano Thank you for pointing out this important issue. As I said in REAME that what this action do is just do some computing and store the result to a path, and you can visit the result as a "service". We use the name "ActionServerless" just use a buzzword to catch more attentions. 

In fact we just generate a result to a file, and it's normal for GitHub users to visit the raw file. Also GitHub has limits on every users usage. 

But anyway, If GitHub would take this as a disruption to their actions service, I'd like to close this project and delete the code.

**Comment by gingerhot** [comment]
Update: I've written an email to GitHub support to confirm this issue.
